Fix AttributeError with aldryn-search when rebuilding index
Note: ALDRYN_NEWSBLOG_SEARCH = False in this configuration

$ python manage.py rebuild_index

WARNING: This will irreparably remove EVERYTHING from your search index in connection 'fr', 'ar', 'default', 'en'.
Your choices after this are to restore from backups or rebuild via the `rebuild_index` command.
Are you sure you wish to continue? [y/N] y
Removing all documents from your index because you said so.
All documents removed.
Indexing 1 titles
Indexing 40 titles
Indexing 41 titles
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/haystack/management/commands/rebuild_index.py", line 26, in handle
    call_command('update_index', **options)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 183, in handle
    return super(Command, self).handle(*items, **options)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/django/core/management/base.py", line 503, in handle
    label_output = self.handle_label(label, **options)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 188, in handle_label
    self.update_backend(label, using)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 233, in update_backend
    do_update(backend, index, qs, start, end, total, verbosity=self.verbosity, commit=self.commit)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/haystack/management/commands/update_index.py", line 96, in do_update
    backend.update(index, current_qs, commit=commit)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/haystack/backends/elasticsearch_backend.py", line 171, in update
    prepped_data = index.full_prepare(obj)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/haystack/indexes.py", line 212, in full_prepare
    self.prepared_data = self.prepare(obj)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/aldryn_search/base.py", line 42, in prepare
    self.prepared_data['text'] = self.get_search_data(obj, current_language, request)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/aldryn_search/search_indexes.py", line 114, in get_search_data
    plugin_text_content = self.get_plugin_search_text(base_plugin, request)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/aldryn_search/search_indexes.py", line 130, in get_plugin_search_text
    plugin_content_bits = get_plugin_index_data(base_plugin, request)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/aldryn_search/helpers.py", line 53, in get_plugin_index_data
    plugin_contents = instance.render_plugin(context=plugin_context)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/cms/models/pluginmodel.py", line 172, in render_plugin
    context = plugin.render(context, instance, placeholder_slot)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/aldryn_newsblog-1.0.10-py3.4.egg/aldryn_newsblog/cms_plugins.py", line 110, in render
    context['articles_list'] = instance.get_articles(request)
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/aldryn_newsblog-1.0.10-py3.4.egg/aldryn_newsblog/models.py", line 375, in get_articles
    if not self.get_edit_mode(request):
  File "/home/trawick/.virtualenvs/serviceinfo-search/lib/python3.4/site-packages/aldryn_newsblog-1.0.10-py3.4.egg/aldryn_newsblog/models.py", line 242, in get_edit_mode
    return (request.toolbar and request.toolbar.edit_mode)
AttributeError: 'WSGIRequest' object has no attribute 'toolbar'